openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
paths:
  /order:
    post:
      summary: Create a new order
      description: Create a new order
      operationId: addOrder
      requestBody:
        description: Create a new order
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /order/{orderId}:
    get:
      summary: Get an existing order
      description: Get an existing order
      operationId: getOrder
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
          description: uuid of the order to get
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        quantity:
          type: integer
          format: int32
          example: 7
        product:
          type: string
          example: "Apple"
      required:
        - quantity
        - product
